# Generated by Django 5.0.4 on 2024-04-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100)),
                ('amenity_description', models.TextField(blank=True, null=True)),
                ('amenity_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('apartment_no', models.CharField(max_length=100)),
                ('apartment_size', models.CharField(max_length=100)),
                ('apartment_status', models.CharField(blank=True, choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_NID', models.CharField(max_length=20)),
                ('owner_contactNo', models.CharField(max_length=15)),
                ('owned_apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resident_name', models.CharField(max_length=100)),
                ('resident_email', models.EmailField(max_length=254)),
                ('resident_NID', models.CharField(max_length=20)),
                ('resident_contactNo', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.owner')),
                ('residing_apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_contactNo', models.CharField(max_length=15)),
                ('checkInDate', models.DateTimeField(auto_now_add=True)),
                ('visited_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint_content', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_description', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.apartment')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
            ],
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
            ],
        ),
        migrations.CreateModel(
            name='AmenityRequest',
            fields=[
                ('amenityReq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied'), ('Not Available', 'Not Available'), ('Under Maintenance', 'Under Maintenance'), ('Closed', 'Closed')], max_length=100, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.amenity')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('serviceReq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In-progress', 'In-progress')], max_length=100, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.service')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Previous-Month-Statement', 'Previous-Month-Statement'), ('Monthly-Statement', 'Monthly-Statement'), ('Yearly-Statement', 'Yearly-Statement')], max_length=100, null=True)),
                ('statement_details', models.TextField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentSystem.resident')),
            ],
        ),
    ]
