# Generated by Django 5.0.4 on 2024-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='amenity_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
