# Generated by Django 5.0.4 on 2024-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentSystem', '0002_amenity_amenity_image_owner_owner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='static/images'),
        ),
    ]
