# Generated by Django 5.0.4 on 2024-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentSystem', '0003_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='static/images'),
        ),
    ]
